/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordAttemptDto
 */
export interface ChangePasswordAttemptDto {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordAttemptDto
     */
    currentPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordAttemptDto
     */
    newPassword?: string | null;
}

export function ChangePasswordAttemptDtoFromJSON(json: any): ChangePasswordAttemptDto {
    return ChangePasswordAttemptDtoFromJSONTyped(json, false);
}

export function ChangePasswordAttemptDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordAttemptDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentPassword': !exists(json, 'currentPassword') ? undefined : json['currentPassword'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
    };
}

export function ChangePasswordAttemptDtoToJSON(value?: ChangePasswordAttemptDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentPassword': value.currentPassword,
        'newPassword': value.newPassword,
    };
}

