/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginAttemptDto
 */
export interface LoginAttemptDto {
    /**
     * 
     * @type {string}
     * @memberof LoginAttemptDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginAttemptDto
     */
    password?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LoginAttemptDto
     */
    rememberMe: boolean;
}

export function LoginAttemptDtoFromJSON(json: any): LoginAttemptDto {
    return LoginAttemptDtoFromJSONTyped(json, false);
}

export function LoginAttemptDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginAttemptDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'rememberMe': json['rememberMe'],
    };
}

export function LoginAttemptDtoToJSON(value?: LoginAttemptDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'password': value.password,
        'rememberMe': value.rememberMe,
    };
}

