/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSecurityInfoDto
 */
export interface UserSecurityInfoDto {
    /**
     * 
     * @type {boolean}
     * @memberof UserSecurityInfoDto
     */
    isAdministrator?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSecurityInfoDto
     */
    mustChangePassword?: boolean;
}

export function UserSecurityInfoDtoFromJSON(json: any): UserSecurityInfoDto {
    return UserSecurityInfoDtoFromJSONTyped(json, false);
}

export function UserSecurityInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSecurityInfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isAdministrator': !exists(json, 'isAdministrator') ? undefined : json['isAdministrator'],
        'mustChangePassword': !exists(json, 'mustChangePassword') ? undefined : json['mustChangePassword'],
    };
}

export function UserSecurityInfoDtoToJSON(value?: UserSecurityInfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isAdministrator': value.isAdministrator,
        'mustChangePassword': value.mustChangePassword,
    };
}

