/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAddRequestDto
 */
export interface UserAddRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserAddRequestDto
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserAddRequestDto
     */
    isAdministrator?: boolean;
}

export function UserAddRequestDtoFromJSON(json: any): UserAddRequestDto {
    return UserAddRequestDtoFromJSONTyped(json, false);
}

export function UserAddRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAddRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isAdministrator': !exists(json, 'isAdministrator') ? undefined : json['isAdministrator'],
    };
}

export function UserAddRequestDtoToJSON(value?: UserAddRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'isAdministrator': value.isAdministrator,
    };
}

