# TODO_JU Audit network access of container at runtime
services:
  vsfh-server:
    build: .
    read_only: true # TODO_JU Make sure this works and that dotnet doesn't need to write anything at runtime
    network: vsfh-net
    ports:
    - "${VSFH_HTTPS_PORT}:7270"
    - "${VSFH_HTTP_PORT}:5299"
    volumes:
    - type: bind
      source: ${VSFH_SHARE_DIRECTORY}
      target: /home/vsfh/shared
      read_only: true # TODO_JU Make sure this works
    - type: bind
      source: /etc/vsfh/appsettings.json
      target: /home/vsfh/vsfh/appsettings.json
      read_only: true # TODO_JU Make sure this works
    - type: bind
      source: /var/lib/vsfh/Database.sqlite
      target: /home/vsfh/vsfh/Database.sqlite
      read_only: false

networks:
  vsfh-net:
    # Specifies that docker/podman should NOT bridge the container to the host,
    # preventing it from accessing the internet or the host's local network.
    # This is a very important security measure and should NOT be removed
    # unless you really, really know what you're doing.
    internal: true
