/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ArchiveFormat,
    AuthenticationFailureDto,
    DirectoryDto,
} from '../models';

export interface FilesDownloadGetRequest {
    path?: string;
    archiveFormat?: ArchiveFormat;
}

export interface FilesDownloadManyPostRequest {
    archiveFormat: ArchiveFormat;
    requestBody?: Array<string>;
}

export interface FilesListingGetRequest {
    path?: string;
    depth?: number;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     */
    async filesDownloadGetRaw(requestParameters: FilesDownloadGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters.path !== undefined) {
            queryParameters['path'] = requestParameters.path;
        }

        if (requestParameters.archiveFormat !== undefined) {
            queryParameters['archiveFormat'] = requestParameters.archiveFormat;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Files/Download`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async filesDownloadGet(requestParameters: FilesDownloadGetRequest, initOverrides?: RequestInit): Promise<void> {
        await this.filesDownloadGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async filesDownloadManyPostRaw(requestParameters: FilesDownloadManyPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.archiveFormat === null || requestParameters.archiveFormat === undefined) {
            throw new runtime.RequiredError('archiveFormat','Required parameter requestParameters.archiveFormat was null or undefined when calling filesDownloadManyPost.');
        }

        const queryParameters: any = {};

        if (requestParameters.archiveFormat !== undefined) {
            queryParameters['archiveFormat'] = requestParameters.archiveFormat;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/Files/DownloadMany`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.requestBody,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async filesDownloadManyPost(requestParameters: FilesDownloadManyPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.filesDownloadManyPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async filesListingGetRaw(requestParameters: FilesListingGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DirectoryDto>> {
        const queryParameters: any = {};

        if (requestParameters.path !== undefined) {
            queryParameters['path'] = requestParameters.path;
        }

        if (requestParameters.depth !== undefined) {
            queryParameters['depth'] = requestParameters.depth;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Files/Listing`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async filesListingGet(requestParameters: FilesListingGetRequest, initOverrides?: RequestInit): Promise<DirectoryDto> {
        const response = await this.filesListingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async filesPathSeparatorGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Files/PathSeparator`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async filesPathSeparatorGet(initOverrides?: RequestInit): Promise<string> {
        const response = await this.filesPathSeparatorGetRaw(initOverrides);
        return await response.value();
    }

}
