/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcceptInviteDto
 */
export interface AcceptInviteDto {
    /**
     * 
     * @type {string}
     * @memberof AcceptInviteDto
     */
    inviteKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AcceptInviteDto
     */
    newPassword?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AcceptInviteDto
     */
    rememberMe: boolean;
}

export function AcceptInviteDtoFromJSON(json: any): AcceptInviteDto {
    return AcceptInviteDtoFromJSONTyped(json, false);
}

export function AcceptInviteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptInviteDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inviteKey': !exists(json, 'inviteKey') ? undefined : json['inviteKey'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
        'rememberMe': json['rememberMe'],
    };
}

export function AcceptInviteDtoToJSON(value?: AcceptInviteDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inviteKey': value.inviteKey,
        'newPassword': value.newPassword,
        'rememberMe': value.rememberMe,
    };
}

