/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ArchiveFormat {
    Tar = 'Tar',
    Zip = 'Zip'
}

export function ArchiveFormatFromJSON(json: any): ArchiveFormat {
    return ArchiveFormatFromJSONTyped(json, false);
}

export function ArchiveFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveFormat {
    return json as ArchiveFormat;
}

export function ArchiveFormatToJSON(value?: ArchiveFormat | null): any {
    return value as any;
}

