/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserListingDto
 */
export interface UserListingDto {
    /**
     * 
     * @type {string}
     * @memberof UserListingDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserListingDto
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserListingDto
     */
    isAdministrator?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserListingDto
     */
    activated?: boolean;
}

export function UserListingDtoFromJSON(json: any): UserListingDto {
    return UserListingDtoFromJSONTyped(json, false);
}

export function UserListingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListingDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isAdministrator': !exists(json, 'isAdministrator') ? undefined : json['isAdministrator'],
        'activated': !exists(json, 'activated') ? undefined : json['activated'],
    };
}

export function UserListingDtoToJSON(value?: UserListingDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'isAdministrator': value.isAdministrator,
        'activated': value.activated,
    };
}

