/* tslint:disable */
/* eslint-disable */
/**
 * VerySimpleFileHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserEditDto
 */
export interface UserEditDto {
    /**
     * 
     * @type {string}
     * @memberof UserEditDto
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserEditDto
     */
    resetPassword: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserEditDto
     */
    isAdministrator?: boolean | null;
}

export function UserEditDtoFromJSON(json: any): UserEditDto {
    return UserEditDtoFromJSONTyped(json, false);
}

export function UserEditDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserEditDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'resetPassword': json['resetPassword'],
        'isAdministrator': !exists(json, 'isAdministrator') ? undefined : json['isAdministrator'],
    };
}

export function UserEditDtoToJSON(value?: UserEditDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'resetPassword': value.resetPassword,
        'isAdministrator': value.isAdministrator,
    };
}

